---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid.fullname" . }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
data:
{{- tpl (.Files.Glob "configmap/**").AsConfig . | nindent 2 }}

